version: '3.8'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "task5"
      POSTGRES_USER: "task5user"
      POSTGRES_PASSWORD: "task5password"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
